#version: '3.8'

services:
  django-app:
    build:
      context: .
    container_name: django-app
    command: gunicorn transcodenexus.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    working_dir: /app
    expose:
      - "8000"
    environment:
      - DEBUG=False

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "8000:8000"
    depends_on:
      - django-app
    volumes:
      - ./ngnix/default.conf:/etc/nginx/conf.d/default.conf:ro
