
version: 1.0

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django-app
    volumes:
      - ./app:/app
    expose:
      - "8000"
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web
